grails-app/domain/canon/Feature.groovy
package canon

import canon.enums.Status

class Feature {

    Language language

    String name
    String description

    Media iconMedia
    String iconTitle
    String iconSubtitle
    Media media

    Status status = Status.DRAFT

    User createdBy
    User modifiedBy
    Date dateCreated
    Date lastUpdated

    static constraints = {
        iconMedia nullable: true
        media nullable: true

        createdBy nullable: true
        modifiedBy nullable: true
    }

    static mapping = {
        description sqlType: "text"
    }
}

grails-app/views/templates/tagLibs/_banner.gsp
<g:set var="compBanner" value="${component?.getAsComponent() as canon.model.comp.BannerComp}" />
<g:if test="${compBanner && compBanner.getBanner().getBannerItems()}">
    <div class="home" id="home">
        <div class="wrap-carousel">
            <div class="owl-carousel owl-home">
                <g:each in="${compBanner.getBanner().getBannerItems()}" var="bannerItem">
                    <div class="item">
                        <div class="bg" data-image="${bannerItem?.background?.getUrl()}" data-copyright="${bannerItem?.background?.getCopyright() ?: ''}"></div>
                        <div class="content">
                            <h1 class="font-light">
                                ${raw(bannerItem?.title)}
                            </h1>
                            <g:link url="${bannerItem?.buttonUrl}" class="btn btn-primary">
                                ${bannerItem?.buttonLabel ?: message(code: "home.button.findADeal.label", default: "Find a deal")}
                            </g:link>
                        </div>
                    </div>
                </g:each>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</g:if>

grails-app/views/templates/tagLibs/_featured_articles.gsp
<%@ page import="canon.enums.Segment; canon.utils.ContentUtils; canon.model.comp.FeaturedArticlesComp" %>
<g:set var="compFeaturedArticles" value="${component?.getAsComponent() as FeaturedArticlesComp}" />
<g:if test="${compFeaturedArticles && compFeaturedArticles.getFeaturedList()?.size() > 0}">
    <g:set var="catName" value="${compFeaturedArticles.category?.translation?.name ?: compFeaturedArticles.category?.name}" />
    <!-- Start Content -->
    <div class="section">
        <div class="container">
            <g:if test="${!compFeaturedArticles.getHideTitle()}">
                <h3 class="title-section">${compFeaturedArticles.title ?: catName ?: message(code: "component.FEATURED_ARTICLES."+compFeaturedArticles.contentType?.name()+".title", default: "Articles")}</h3>
            </g:if>
            <div class="wrap-carousel-mobile">
                <div class="row">
                    <g:set var="fFeaturedArticle" value="${compFeaturedArticles.getFeaturedList().get(0)}" />
                    <div class="col-sm-12">
                        <!-- Start Post Item -->
                        <div class="post-item match-height">
                            <span class="badge left gray">${fFeaturedArticle.getMainCategory(segment as String)?.translation?.name ?: fFeaturedArticle.getMainCategory(segment as String)?.name}</span>
                            <div class="row wrap-vertical-content">
                                <div class="col-sm-6 getheight">
                                    <div class="wrap-image bg-img-post">
                                        <g:set var="articleBgPos" value="${fFeaturedArticle.getBanner()?.getFeaturedLargeX() ? 'background-position: ' + fFeaturedArticle.getBanner()?.getFeaturedLargeX() + '%;' : ''}" />
                                        <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'Details' }" id="${fFeaturedArticle?.slug}" params="${params}">
                                            <img src="${fFeaturedArticle.getBanner()?.getUrl()}" alt="${fFeaturedArticle?.headline}" />
                                        </g:link>
                                    </div>
                                </div>
                                <div class="col-sm-6 desc">
                                    <div class="vertical-middle">
                                        <div class="content left-medium">
                                            <h3 class="title">
                                                <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'Details' }" id="${fFeaturedArticle?.slug}" params="${params}">
                                                    ${raw(fFeaturedArticle?.headline)}
                                                </g:link>
                                            </h3>
                                            <p><g:set var="firstTextComponent" value="${fFeaturedArticle.getFirstTextComponent()?.component?.getAsComponent() as canon.model.comp.TextComp}" />
                                                <strong><g:formatDate date="${fFeaturedArticle.publishedDate}" format="dd MMMM yyyy" /></strong>
                                                - ${raw(ContentUtils.truncate(fFeaturedArticle?.deck ?: firstTextComponent?.getContent()))}
                                            </p>
                                            <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'Details' }" id="${fFeaturedArticle.slug}" params="${params}" class="btn btn-primary">
                                                <g:message code="component.FEATURED_ARTICLES.readMore.label" default="Read More" />
                                            </g:link>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- End Post Item -->
                    </div>
                    <g:if test="${compFeaturedArticles.getFeaturedList()?.size() > 1}">
                        <g:set var="sFeaturedArticle" value="${compFeaturedArticles.getFeaturedList().get(1)}" />
                        <div class="col-md-8 col-sm-7">
                            <!-- Start Post Item -->
                            <div class="post-item match-height">
                                <span class="badge left gray">${sFeaturedArticle.getMainCategory(segment as String)?.translation?.name ?: sFeaturedArticle.getMainCategory(segment as String)?.name}</span>
                                <div class="wrap-image bg-img-post">
                                    <g:set var="articleBgPos" value="${sFeaturedArticle.getBanner()?.getFeaturedMediumX() ? 'background-position: ' + sFeaturedArticle.getBanner()?.getFeaturedMediumX() + '%;' : ''}" />
                                    <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'Details' }" id="${sFeaturedArticle.slug}" params="${params}">
                                        <img src="${sFeaturedArticle.getBanner().getUrl()}" alt="${sFeaturedArticle?.headline}" />
                                    </g:link>
                                </div>
                                <div class="content text-left">
                                    <h5 class="title">
                                        <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'Details' }" id="${sFeaturedArticle.slug}" params="${params}">
                                            ${raw(sFeaturedArticle?.headline)}
                                        </g:link>
                                    </h5>
                                    <g:set var="firstTextComponent" value="${sFeaturedArticle.getFirstTextComponent()?.component?.getAsComponent() as canon.model.comp.TextComp}" />
                                    <p>${raw(ContentUtils.truncate(sFeaturedArticle?.deck ?: firstTextComponent?.getContent()))}</p>
                                </div>
                            </div>
                            <!-- End Post Item -->
                        </div>
                    </g:if>
                    <g:if test="${compFeaturedArticles.getFeaturedList()?.size() > 2}">
                        <g:set var="tFeaturedArticle" value="${compFeaturedArticles.getFeaturedList().get(2)}" />
                        <div class="col-md-4 col-sm-5">
                            <!-- Start Post Item -->
                            <div class="post-item match-height">
                                <span class="badge left gray">${tFeaturedArticle.getMainCategory(segment as String)?.translation?.name ?: tFeaturedArticle.getMainCategory(segment as String)?.name}</span>
                                <div class="wrap-image bg-img-post">
                                    <g:set var="articleBgPos" value="${tFeaturedArticle.getBanner().getFeaturedSmallX() ? 'background-position: ' + tFeaturedArticle.getBanner().getFeaturedSmallX() + '%;' : ''}" />
                                    <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'Details' }" id="${tFeaturedArticle.slug}" params="${params}">
                                        <img src="${tFeaturedArticle.getBanner()?.getUrl()}" alt="${tFeaturedArticle?.headline}" />
                                    </g:link>
                                </div>
                                <div class="content text-left">
                                    <h5 class="title">
                                        <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'Details' }" id="${tFeaturedArticle.slug}" params="${params}">
                                            ${raw(tFeaturedArticle?.headline)}
                                        </g:link>
                                    </h5>
                                    <strong><g:formatDate date="${tFeaturedArticle.publishedDate}" format="dd MMMM yyyy" /></strong>
                                </div>
                            </div>
                            <!-- End Post Item -->
                        </div>
                    </g:if>
                </div>
            </div>
            <g:if test="${!compFeaturedArticles.getHideViewAll()}">
                <div class="text-right">
                    <g:link mapping="${ compFeaturedArticles.contentType?.name()?.toLowerCase()+'List' }" params="[site: params?.site, segment: segment, category: compFeaturedArticles.category?.slug]" class="btn btn-default btn-sm more">
                        <g:message code="component.FEATURED_ARTICLES.${compFeaturedArticles.contentType?.name()}.viewAll.label" default="View all {0} articles" args="[catName?:'']" />
                        <span class="fa fa-angle-right"></span>
                    </g:link>
                </div>
            </g:if>
        </div>
    </div>
    <!-- End Content -->
    <div class="clearfix"></div>
</g:if>

grails-app/views/templates/tagLibs/_featured_products.gsp
<%@ page import="canon.model.comp.FeaturedProductsComp" %>
<g:set var="compFeaturedProduct" value="${component?.getAsComponent() as FeaturedProductsComp}" />
<g:if test="${compFeaturedProduct && compFeaturedProduct.getFeaturedList()?.size() > 0}">
    <!-- Start Content -->
    <div class="section products" id="product">
        <div class="container">
            <div class="row">
                <g:each var="featuredProduct" in="${compFeaturedProduct.getFeaturedList()}" status="i">
                    <g:if test="${compFeaturedProduct.getFeaturedList()?.size() - 1 != i}">
                        <div class="col-sm-4 col-xs-6">
                            <!-- Start Post Item -->
                            <div class="post-item match-height">
                                <span class="badge left"><g:message code="home.tag.new.label" default="New"/></span>
                                <img src="${featuredProduct?.defaultMedia?.media?.url}" alt="">
                                <div class="content">
                                    <h3 class="title">
                                        <g:link controller="product" action="show" id="${featuredProduct?.slug}" params="[segment: params?.segment, site: params?.site, lang: params?.lang]">
                                            ${featuredProduct?.name}
                                        </g:link>
                                    </h3>
                                </div>
                            </div>
                            <!-- End Post Item -->
                        </div>
                    </g:if>
                    <g:else>
                        <div class="col-sm-12 col-xs-6">
                            <!-- Start Post Item -->
                            <div class="post-item match-height">
                                <span class="badge left"><g:message code="home.tag.promotion.label" default="Promotion"/></span>
                                <div class="row wrap-vertical-content">
                                    <div class="col-sm-6 getheight">
                                        <img src="${featuredProduct?.defaultMedia?.media?.url}" alt="">
                                    </div>
                                    <div class="col-sm-6 desc">
                                        <div class="vertical-middle">
                                            <div class="content">
                                                <h3 class="title">
                                                    <g:link controller="product" action="show" params="[id: featuredProduct?.slug]">
                                                        ${featuredProduct?.name}
                                                    </g:link>
                                                </h3>
                                                <p class="hide-small">
                                                    ${featuredProduct?.description}
                                                </p>
                                                <g:link class="btn btn-primary hide-small" controller="product" action="show" params="[id: featuredProduct?.slug]">
                                                    <g:message code="home.button.viewProduct.label" default="View Product"/>
                                                </g:link>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- End Post Item -->
                        </div>
                    </g:else>
                </g:each>
            </div>

            <div class="text-right">
                <g:link class="btn btn-default btn-sm more" controller="product" action="category" params="[segment: params?.segment, site: params?.site, lang: params?.lang]">
                    <g:message code="component.FEATURED_PRODUCTS.viewAll.label" default="View all products"/> <span class="fa fa-angle-right"></span>
                </g:link>
            </div>
        </div>
    </div>
    <!-- End Content -->
    <div class="clearfix"></div>
</g:if>

grails-app/views/templates/tagLibs/_hero.gsp
<g:set var="compHero" value="${component?.getAsComponent() as canon.model.comp.HeroComp}" />
<g:if test="${compHero}">
    <!-- Start Section -->
    <div class="section">
        <div class="container">
            <div class="img-article"><img src="${compHero?.imageUrl}" class="img-responsive" alt=""/></div>
        </div>
    </div>
    <!-- End Section -->
</g:if>

grails-app/views/templates/tagLibs/_prod_award.gsp
<%@ page import="canon.Award; canon.ProductAward" %>
<g:set var="compProdAward" value="${component?.getAsComponent() as canon.model.comp.ProdAwardComp}" />
<g:if test="${product?.activeAwards}">
    <!-- Start Section Detail -->
    <div class="section">
        <div class="container">
            <!-- Start Award -->
            <h1 class="title-section text-center"><g:message code="product.overview.awards.label" default="Awards"/></h1>
            <div class="row main-row-slide">
                <div class="col-md-10 col-md-offset-1">
                    <!-- Start Item Features -->
                    <div class="row slide-in-small">
                    <g:each in="${product?.activeAwards as java.util.List<canon.Award>}" var="award">
                        <div class="col-sm-4 col-xs-12 margin-bottom20">
                            <div class="box-panel">
                                <img src="${award?.imageUrl}" alt="">
                            </div>
                        </div>
                    </g:each>
                    <!-- End Item Features -->
                </div>
            </div>
            <!-- End Awards -->
        </div>
    </div>
    <!-- End Section Detail -->
</g:if>

grails-app/views/templates/tagLibs/_prod_banner.gsp
<!-- Start Content -->
<g:set var="compProdBanner" value="${component?.getAsComponent() as canon.model.comp.ProdBannerComp}" />
<div class="section-demo bg" data-image="${compProdBanner?.bgUrl}">
    <div class="overlay"></div>
    <div class="container content-demo">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="content">
                    <div class="row">
                        <div class="col-sm-6 col-sm-push-6">
                            <img src="${product?.getDefaultMedia()?.media?.url}" class="img-responsive" alt=""/>
                        </div>
                        <div class="col-sm-6 col-sm-pull-6">
                            <h1 class="title">${product?.name}</h1>
                            <p class="opacity50">
                                ${compProdBanner?.desc ?: product?.subText}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Content -->

<div class="clearfix"></div>

grails-app/views/templates/tagLibs/_prod_desc.gsp
<g:set var="compProdDesc" value="${component?.getAsComponent() as canon.model.comp.ProdDescComp}" />
<!-- Start Section Detail -->
<div class="content-detail m-padding-bottom30">
    <div class="container">

        <!-- Start Content -->
        <div class="row main-content">
            <div class="col-md-8 col-md-offset-2">
                <h1 class="title">
                    ${compProdDesc?.getNewSubText() ?: product?.subText}
                </h1>
                <div class="desc">
                    ${compProdDesc?.getNewDesc() ?: product?.description}
                </div>
            </div>
        </div>
        <!-- End Content -->
    </div>
</div>
<!-- End Section Detail -->

grails-app/views/templates/tagLibs/_prod_features.gsp
<%@ page import="canon.FeatureComponent; canon.ProductFeature" %>
<!-- Start Content -->
<g:set var="compProdPromotion" value="${component?.getAsComponent() as canon.model.comp.ProdFeaturesComp}" />
<g:set var="productFeatures" value="${compProdPromotion?.featureList}"/>
<g:if test="${productFeatures}">
    <!-- Start Section Detail -->
    <div class="section">
        <div class="container">
            <!-- Start Features -->
            <h1 class="title-section text-center">
                <g:message code="product.overview.features.label" default="Features"/>
            </h1>
            <div class="row main-row-slide">
                <div class="col-md-10 col-md-offset-1">
                    <!-- Start Item Feature -->
                    <div class="row slide-in-small">
                        <g:each in="${productFeatures}" var="productFeature" status="i">
                            <div class="col-sm-4 col-xs-12 margin-bottom20">
                                <div class="box-panel match-height ${i == 0 ? 'active':''} text-left">
                                    <div class="content">
                                        <img src="${productFeature?.iconMedia?.url}" alt="" class="img-gray">
                                        <h4 class="title">${productFeature?.iconTitle}</h4>
                                        <p>${productFeature?.iconSubtitle}</p>
                                    </div>
                                    <a href="#feature-content__${productFeature?.id}" class="link" data-toggle="tab"></a>
                                </div>
                            </div>
                        </g:each>
                    </div>
                    <!-- End Item Feature -->
                </div>
            </div>
            <!-- End Content -->
        </div>
    </div>
    <!-- End Section Detail -->
    <!-- Start Section Detail -->
    <div class="section">
        <div class="container center-small">
            <div class="tab-content">
                <g:each in="${productFeatures}" var="productFeature" status="i">
                    <!-- Start Tab Pane -->
                    <div class="tab-pane fade ${i == 0 ? 'in active' : ''}" id="feature-content__${productFeature?.id}">
                        <div class="row">
                            ${raw(productFeature?.description)}
                        </div>
                    </div>
                    <!-- End Tab Pane -->
                </g:each>
            </div>
        </div>
    </div>
    <!-- End Section Detail -->
    <div class="clearfix"></div>
</g:if>

grails-app/views/templates/tagLibs/_prod_image.gsp
<%@ page import="canon.ProductMedia" %>
<!-- Start Content -->
<g:set var="compProdPromotion" value="${component?.getAsComponent() as canon.model.comp.ProdImageComp}" />
<g:set var="productMedias" value="${product?.productMedias as java.util.List<canon.ProductMedia>}"/>
<g:if test="${productMedias}">
    <!-- Start Section -->
    <div class="section padding-top0 padding-bottom0">
        <div class="container">
            <!-- Start Wrap Views -->
            <div class="wrap-view">
                <ul class="control">
                    <li>
                        <a href="#zoomin"><span class="fa fa-search"></span></a>
                        <g:message code="product.overview.zoom.label" default="Zoom"/>
                    </li>
                    <li class="active">
                        <a href="#rotate" class="custom_next"><span class="fa fa-rotate-left"></span></a>
                        <g:message code="product.overview.360view.label" default="360º View"/>
                    </li>
                </ul>

                <!-- Start Load 360 -->
                <div id="rotate" class="content-view rotate-img threesixty hide">
                    <div class="spinner">
                        <span><g:message code="product.overview.zeroPercent.label" default="0%"/></span>
                    </div>
                    <ol class="threesixty_images"></ol>
                </div>
                <!-- End Load 360 -->

                <!-- Start Zoom In -->
                <div id="zoomin" class="content-view wrap-zoomin hide">
                    <div class="panzoom">
                        <img src="" class="img-zoom">
                    </div>
                    <div class="buttons">
                        <button class="zoom-in btn btn-primary btn-sm"><span class="fa fa-plus"></span></button>
                        <button class="zoom-out btn btn-primary btn-sm"><span class="fa fa-minus"></span></button>
                        <button class="reset btn btn-primary btn-sm"><span class="fa fa-refresh"></span></button>
                    </div>
                </div>
                <!-- End Zoom In -->
            </div>
            <!-- End Wrap Views -->

            <!-- Start Item Views -->
            <div class="owl-carousel owl-view">
                <g:each in="${productMedias}" var="productMedia">
                    <div class="item ${productMedia?.isDefault ? 'active': '' } list-view" data-type="${productMedia?.media?.mediaType?.name()?.toLowerCase()}" data-path="${productMedia?.media?.url}">
                        <div class="content">
                            <a href="#">
                                <img src="${productMedia?.media?.url}" alt="" />
                            </a>
                        </div>
                    </div>
                </g:each>
            </div>
            <!-- End Item Views -->
        </div>
    </div>
    <!-- End Section -->
    <div class="clearfix"></div>
</g:if>

grails-app/views/templates/tagLibs/_prod_promotion.gsp
<g:set var="compProdPromotion" value="${component?.getAsComponent() as canon.model.comp.ProdPromotionComp}" />
<g:if test="${product?.activePromotion}">
    <!-- Start Content -->
    <div class="section">
        <div class="container">
            <!-- Start Promotion Box -->
            <div class="promotion-box">
                <h1 class="title"><g:message code="product.overview.promotion.label" default="Promotion"/></h1>
                <p>
                    ${raw(product?.activePromotion?.promotionDesc)}
                </p>
                <g:link class="btn btn-primary" controller="promotion" action="index">
                    <g:message code="product.overview.findOutMore.label" default="Find Out More"/>
                </g:link>
            </div>
            <!-- End Promotion Box -->
        </div>
    </div>
    <!-- End Content -->
    <div class="clearfix"></div>
</g:if>

grails-app/views/templates/tagLibs/_prod_related_reads.gsp
<g:set var="compProdRelatedReads" value="${component?.getAsComponent() as canon.model.comp.ProdRelatedReadsComp}" />
<g:if test="${compProdRelatedReads?.articles}">
    <!-- Start Section -->
    <div class="section">
        <div class="container">
            <!-- Start Features -->
            <h1 class="title-section text-center"><g:message code="product.overview.relatedReads.label" default="Related Reads"/></h1>
            <div class="wrap-carousel-in-small">
                <div class="row carousel-in-small">
                    <g:each in="${compProdRelatedReads?.articles}" var="article">
                        <div class="col-sm-4 col-xs-12">
                            <!-- Start Post Item -->
                            <div class="post-item bg-mode">
                                <span class="badge gray left hide-small">${article?.articleTagName}</span>
                                <img src="${article?.articleBgUrl}" alt="" />
                                <div class="content">
                                    <h3 class="title">${article?.articleTitle}</h3>
                                </div>
                                <g:link class="link" controller="page" action="show" id="${article?.articleSlug}" params="params"/>
                            </div>
                            <!-- End Post Item -->
                        </div>
                    </g:each>
                </div>
            </div>
            <!-- End Content -->
        </div>
    </div>
    <!-- End Section -->

    <div class="clearfix"></div>
</g:if>

grails-app/views/templates/tagLibs/_text.gsp
<g:set var="compText" value="${component?.getAsComponent() as canon.model.comp.TextComp}" />
<g:if test="${compText && org.apache.commons.lang.StringUtils.isNotBlank(compText?.getContent())}">
    <!-- Start Section -->
    <div class="section">
        <div class="container">
            ${raw(compText?.getContent())}
        </div>
    </div>
    <!-- End Section -->
</g:if>

grails-app/views/templates/tagLibs/_text_right.gsp
<g:set var="compTextImage" value="${component?.getAsComponent() as canon.model.comp.TextImageComp}" />
<!-- Start Section -->
<div class="section">
    <div class="row">
        <div class="col-md-6 component-text-left-image">
            <img src="${compTextImage?.getImageUrl() ?: ''}" class="img-responsive" alt="" data-copyright="${compTextImage?.getCopyright() ?: ''}" />
        </div>
        <div class="col-md-6 component-text-left-content">
            ${raw(compTextImage?.getContent() ?: '')}
        </div>
    </div>
</div>
<!-- End Section -->