grails-app/controllers/canon/admin/AdminProductController.groovy
package canon.admin

import canon.Flow
import canon.Language
import canon.Product
import canon.ProductRelation
import canon.ProductSellingPoint
import canon.ProductDetail
import canon.Site
import canon.User
import canon.WorkFlow
import canon.enums.ComponentType
import canon.enums.RelationType
import canon.enums.Segment
import canon.enums.Status
import canon.model.Component
import canon.model.DataResult
import grails.converters.JSON
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AdminProductController {

    static allowedMethods = [archiveProducts: "POST"]

    def adminProductService
    def adminCategoryService
    def springSecurityService

    def index() {
        if (!params.get("status")) params.status = Status.PUBLISHED.name()

        String dateFormat = message(code: 'admin.default.view.date.format', default: 'd MMM yyyy')
        Date dateFrom = params?.dateFrom ? params?.date('dateFrom', dateFormat) : null
        Date dateTo = params?.dateTo ? params?.date('dateTo', dateFormat) + 1 : null

        def paramsOverride = [:]
        paramsOverride.put("dateFrom", dateFrom)
        paramsOverride.put("dateTo", dateTo)

        def productList = adminProductService.getProductList(params, paramsOverride)
        def productCount = adminProductService.getProductCount(params, paramsOverride)

        def countByStatus = [:]
        def statusList = [Status.PUBLISHED, Status.DRAFT, Status.ARCHIVED]
        statusList.each {
            countByStatus.put(it.name(), adminProductService.getProductCount(params, [status: it.name(), dateFrom: dateFrom, dateTo: dateTo]))
        }

        [
                productList: productList,
                productCount: productCount,
                statusList: statusList,
                countByStatus: countByStatus
        ]
    }

    def create() {
        User user = springSecurityService.getCurrentUser()

        Site masterDataSite = Site.findByIsDefault(Boolean.TRUE)

        Product newProduct = new Product()
        newProduct.site = masterDataSite

        newProduct.addToProductDetails(new ProductDetail(site: masterDataSite))

        [
                product: newProduct,
                user: user,
                flows: Flow.list(sort: "name"),
                languageList: Language.list(sort: "name"),
                siteList: Site.list(sort: "name")
        ]
    }

    def location() {
        Product product = Product.findById(params.long("id"))
        User user = springSecurityService.getCurrentUser()
        def flow = Flow.findByName("Product Workflow")
        def workFlowList = WorkFlow.findAllByFlow(flow)
        def authorList = User.list(sort: "username")
        def currentWorkFlow = WorkFlow.findByFlowAndIsStart(flow, Boolean.FALSE)
        def languageList = Language.list(sort: "name")

        [
                product: product,
                user: user,
                flow: flow,
                workFlowList: workFlowList,
                authorList: authorList,
                currentWorkFlow: currentWorkFlow,
                languageList: languageList
        ]
    }

    def show() {
        Product product = Product.findById(params.long("id"))
        User user = springSecurityService.getCurrentUser()
        def flow = Flow.findByName("Product Workflow")
        def workFlowList = WorkFlow.findAllByFlow(flow)
        def authorList = User.list(sort: "username")
        def currentWorkFlow = WorkFlow.findByFlowAndIsStart(flow, Boolean.FALSE)
        def languageList = Language.list(sort: "name")

        [
                product: product,
                user: user,
                flow: flow,
                workFlowList: workFlowList,
                authorList: authorList,
                currentWorkFlow: currentWorkFlow,
                languageList: languageList
        ]
    }

    @Deprecated
    def delete() {

    }

    @Transactional
    def save(Product prd) {
        if (prd == null) {
            transactionStatus.setRollbackOnly()
            return
        }

        Product product = adminProductService.saveProduct(params, prd)

        if (product.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond product.errors, view:'create'
            return
        }

        if (params?.flow as String == 'NEXT'){
            redirect action: "index"
        }else {
            redirect(action: "edit", id: product?.id)
        }
    }

    def edit(Product product) {
        User user = springSecurityService.getCurrentUser()
        def flow = Flow.findByName("Product Workflow")
        def workFlowList = WorkFlow.findAllByFlow(flow)
        def authorList = User.list(sort: "username")
        def currentWorkFlow = WorkFlow.findByFlowAndIsStart(flow, Boolean.TRUE)
        def languageList = Language.list(sort: "name")

        List<Site> siteList = Site.list(sort: "name")

        def consumerList = adminCategoryService.getLowestLevelCategories(Segment.CONSUMER)
        def businessList = adminCategoryService.getLowestLevelCategories(Segment.BUSINESS)

        def relatedProducts =[]
        def relatedConsumable =[]
        def relatedAccessories =[]
        product?.productRelations?.each { ProductRelation pr ->
            if (pr.relationType == RelationType.PRODUCT) relatedProducts.add(pr)
            else if (pr.relationType == RelationType.CONSUMABLE) relatedConsumable.add(pr)
            else relatedAccessories.add(pr)
        }

        [
                product: product,
                user: user,
                flow: flow,
                workFlowList: workFlowList,
                authorList: authorList,
                currentWorkFlow: currentWorkFlow,
                languageList: languageList,
                siteList: siteList,
                consumerList: consumerList,
                businessList: businessList,
                productRelationMap: [
                        product: relatedProducts,
                        consumable: relatedConsumable,
                        accessories: relatedAccessories
                ]
        ]
    }

    @Transactional
    def update(Product prd) {
        if (prd == null) {
            transactionStatus.setRollbackOnly()
            return
        }

        Product product = adminProductService.updateProduct(params, prd)

        if (product.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond product.errors, view:'edit'
            return
        }

        if (params?.flow as String == 'NEXT'){
            redirect action: "index"
        }else {
            redirect(action: "edit", id: product?.id)
        }
    }

    @Transactional
    def archiveProducts() {
        adminProductService.archiveProducts(params?.list('ids'))
    }
	
	@Transactional
	def restoreProducts() {
		adminProductService.restoreProducts(params?.list('ids'))
	}

    def inline() {
        List<Component> componentList = new ArrayList<>()
        componentList.add(new Component(ComponentType.IMAGE,
                [title: "Photo 1: A vast poppy field against the evening sun",
                 caption: "EOS 5D Mark III/ EF24-105mm f/4L IS USM/ FL: 47mm/ Aperture-priority AE (f/16, 1/25 sec, EV+1.3)/ ISO 200/ WB: White fluorescent light<br>Date of shoot: Late May<br>Photo by Rika Takemoto",
                 copyright: "",
                 imageUrl: "/assets/article/img5.jpg",
                 mediaId: null], 0))
        componentList.add(new Component(ComponentType.TEXT, [content: "Step 1: Shoot downward from a high position<br />\n" +
                "                                        I aimed to create a dramatic image by framing the field of poppies together with the evening sun. The field extended all the way into the background, and in order to bring out that sense of scale, I initially shot at eye level, using a tripod. However, that made the elements in the frame look very scattered.\n" +
                "                                        I realized that I needed to create a point of interest in the frame by framing the image so that the poppies in front of me appeared larger and closer. Therefore, I found a location where there were some tall poppies directly in front of me, and also adjusted my tripod so that it was at waist level.\n" +
                "                                        I had a few different shooting positions in mind, but I eventually chose this one because it provided a good compositional balance between the height of the sun, the silhouettes of the mountains and the poppies in the foreground."], 1))
        componentList.add(new Component(ComponentType.IMAGE,
                [title: "Photo 2: Lilies illuminated by the glow of the evening sun",
                 caption: "EOS 6D/ EF16-35mm f/4L IS USM/ FL: 16mm/ Manual exposure (f/9, 1/200 sec, EV-1.0)/ ISO 100/ WB: Auto<br />Date of shoot: mid-Jun<br />Photo by Yoshiki Fujiwara",
                 copyright: "",
                 imageUrl: "/assets/article/img7.jpg",
                 mediaId: null], 2))
        componentList.add(new Component(ComponentType.TEXT_LEFT,
                [content: "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. " +
                        "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>",
                 imageUrl: "/assets/snippets/img/placeholder-600x400.png",
                 mediaId: null], 3))
        componentList.add(new Component(ComponentType.TEXT_RIGHT,

grails-app/views/adminProduct/_selling_point.gsp
<script id="selling-point-template" type="x-tmpl-mustache">
    <div class="input-group crud margin-bottom10 {{timestamp}} ">
        <input type="text" name="sellingPoints[]" class="form-control" style="background-color:white;" readonly value="{{content}}" >
        <div class="input-group-btn">
            <button class="btn btn-default selling-point-remove" type="button" temp="{{timestamp}}"><span class="fa fa-trash"></span></button>
        </div>
    </div>
</script>

grails-app/views/adminProduct/_workFlow.gsp
<div class="ibox-content">
    <g:hiddenField name="username" value="${user.username}"/>
    <div class="form-group margin-bottom20">
        <label><g:message code="admin.workflow.select.label" default="Select Workflow"/></label>
        <g:if test="${actionName == 'create'}">
            <g:select class="form-control js-flow-selector" name="flow" from="${flows}" data-url="${createLink(controller: 'adminFlow', action: 'getWorkflowByFlow')}" data-get-user="${createLink(controller: 'adminUser', action: 'findAll')}"
                      optionKey="id" optionValue="name" noSelection="['': message(code: 'admin.workflow.select.label', default: 'Select Workflow')]"/>
        </g:if>
    </div>
    <g:if test="${actionName == 'create'}">
        <div class="row js-workflow-list"></div>
    </g:if>
</div>

grails-app/views/adminProduct/create.gsp
<%--
  Created by IntelliJ IDEA.
  User: marjan
  Date: 11/12/17
  Time: 18.29
--%>

<%@ page import="canon.enums.Status" contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title><g:message code="admin.dashboard.title" default="Admin Dashboard"/></title>
    <meta name="layout" content="admin"/>
    <g:render template="/adminProduct/selling_point"/>
</head>

<body>
<!-- Start Page Heading -->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2><g:message code="admin.product.create.createANewProduct.label" default="Create a new product"/></h2>
        <ol class="breadcrumb">
            <li>
                <g:link controller="adminProduct" action="index"><g:message code="admin.product.label" default="Product"/></g:link>
            </li>
            <li>
                <g:link controller="adminProduct" action="index"><g:message code="admin.product.list.label" default="Product List"/></g:link>
            </li>
            <li class="active">
                <strong><g:message code="admin.product.addNew.label" default="Add New Product"/></strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>
<!-- End Page Heading -->
<g:hasErrors bean="${this.product}">
    <ul class="errors" role="alert">
        <g:eachError bean="${this.product}" var="error">
            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
        </g:eachError>
    </ul>
</g:hasErrors>
<g:form controller="adminProduct" action="save" method="POST">
    <g:render template="form_content"
              model="[product: product, languageList: languageList, siteList: siteList, user: user, flows: flows, currentWorkflow: currentWorkFlow]" />
</g:form>
    <content tag="footer">
        <div class="pull-right">
            <button class="btn btn-default margin-left10"><g:message code="admin.default.cancel.label" default="Cancel"/></button>
            <button class="btn btn-primary margin-left10 js-submit-form" data-flow="NO_CHANGES"><g:message code="admin.default.saveChanges.label" default="Save Changes"/></button>
            <button class="btn btn-primary margin-left10 js-submit-form" data-flow="NEXT"><g:message code="admin.default.submit.label" default="Submit"/></button>
        </div>
    </content>
</body>
</html>

grails-app/views/adminProduct/edit.gsp
<%--
  Created by IntelliJ IDEA.
  User: muyalif
  Date: 16/12/17
  Time: 03.35
--%>

<%@ page import="canon.enums.Status" contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title><g:message code="admin.dashboard.title" default="Admin Dashboard"/></title>
    <meta name="layout" content="admin"/>
</head>

<body>
<!-- Start Page Heading -->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Create a new product</h2>
        <ol class="breadcrumb">
            <li>
                <g:link controller="adminProduct" action="index">Product</g:link>
            </li>
            <li>
                <g:link controller="adminProduct" action="index">Product List</g:link>
            </li>
            <li class="active">
                <strong>Add New Product</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>
<!-- End Page Heading -->
<g:hasErrors bean="${this.product}">
    <ul class="errors" role="alert">
        <g:eachError bean="${this.product}" var="error">
            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
        </g:eachError>
    </ul>
</g:hasErrors>
<g:form controller="adminProduct" action="update" id="${product?.id}" method="PUT">
    <g:render template="form_content"
              model="[product: product, languageList: languageList, siteList: siteList, consumerList: consumerList, businessList: businessList, productRelationMap: productRelationMap]" />
</g:form>
<content tag="footer">
    <div class="pull-right">
        <button class="btn btn-default margin-left10">Cancel</button>
        <button class="btn btn-primary margin-left10 js-submit-form" data-flow="NO_CHANGES">Save Changes</button>
        <button class="btn btn-primary margin-left10 js-submit-form" data-flow="NEXT">Submit</button>
    </div>
</content>
</body>
</html>

grails-app/views/adminProduct/location.gsp
<%--
  Created by IntelliJ IDEA.
  User: marjan
  Date: 11/12/17
  Time: 18.29
--%>

<%@ page import="canon.enums.Status" contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title><g:message code="admin.dashboard.title" default="Admin Dashboard"/></title>
    <meta name="layout" content="admin"/>
</head>

<body>

<!-- Start Page Heading -->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>Location & Language Selection</h2>
        <ol class="breadcrumb">
            <li>
                <g:link controller="adminProduct" action="index">Product</g:link>
            </li>
            <li>
                <g:link controller="adminProduct" action="index">Product List</g:link>
            </li>
            <li class="active">
                <strong>Location & Language</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>
<!-- End Page Heading -->

<!-- Start Content -->
<div class="wrapper wrapper-content">
    <!-- Start Ibox -->
    <div class="ibox-content margin-bottom60">
        <div class="row">
            <div class="col-sm-8">
                <form class="form-inline">
                    <div class="form-group margin-bottom20">
                        <label>Filter by</label>
                        <select class="form-control w100">
                            <option>All Locations</option>
                            <option>Option 1</option>
                            <option>Option 2</option>
                            <option>Option 3</option>
                            <option>Option 4</option>
                        </select>
                    </div>
                    <div class="form-group margin-bottom20">
                        <label>Date range</label>
                        <select class="form-control">
                            <option>14 Sept 2017</option>
                            <option>13 Sept 2017</option>
                            <option>12 Sept 2017</option>
                            <option>11 Sept 2017</option>
                            <option>10 Sept 2017</option>
                            <option>9 Sept 2017</option>
                        </select>
                    </div>
                    <div class="form-group margin-bottom20">
                        <label>to</label>
                        <select class="form-control">
                            <option>14 Sept 2017</option>
                            <option>13 Sept 2017</option>
                            <option>12 Sept 2017</option>
                            <option>11 Sept 2017</option>
                            <option>10 Sept 2017</option>
                            <option>9 Sept 2017</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="col-sm-4">
                <div class="input-group"><input type="text" placeholder="Search keyword" class="input-sm form-control"> <span class="input-group-btn">
                    <button type="button" class="btn btn-sm btn-primary">Search</button> </span></div>
            </div>
        </div>
        <div class="row margin-top30">
            <div class="col-sm-6">
                <div data-toggle="buttons" class="btn-group">
                    <label class="btn btn-sm btn-white"> <input type="radio" id="option1" name="options"> Published (120)</label>
                    <label class="btn btn-sm btn-white active"> <input type="radio" id="option2" name="options"> Draft (120)</label>
                    <label class="btn btn-sm btn-white"> <input type="radio" id="option3" name="options"> Archive (120)</label>
                    <label class="btn btn-sm btn-white"> <input type="radio" id="option4" name="options"> Trash (0)</label>
                </div>
            </div>
            <div class="col-sm-6 text-right">
                <div data-toggle="buttons" class="btn-group">
                    <label class="btn btn-sm btn-white"> <input type="radio" id="option5" name="options"> Duplicate</label>
                    <label class="btn btn-sm btn-white"> <input type="radio" id="option6" name="options"> Delete</label>
                    <label class="btn btn-sm btn-white"> <input type="radio" id="option7" name="options"> Move to Archive</label>
                </div>
            </div>
        </div>
        <div class="table-responsive margin-top50">
            <table class="table table-striped sortable">
                <thead>
                <tr>

                    <th class="input"><input type="checkbox" id="checkall" class="i-checks" name="input[]"></th>
                    <th data-sort="string" class="sort">Location — Language</th>
                    <th data-sort="string" class="sort">Category</th>
                    <th data-sort="string" class="sort">Publish Date</th>
                    <th data-sort="string" class="sort">Archive Date</th>
                    <th data-sort="string" class="sort">Created By</th>
                    <th data-sort="string" class="sort">Workflow Status</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td><a href="#" class="single-link">Master Copy — EN</a></td>
                    <td>Digital SLR (EOS)</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Preparer</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td><a href="#" class="single-link">Singapore — EN</a></td>
                    <td>Digital SLR (EOS)</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Preparer</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        Hongkong — EN
                    </td>
                    <td>Digital SLR (EOS)</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        Hongkong — CH
                    </td>
                    <td>Digital SLR (EOS)</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        India — EN
                    </td>
                    <td>DSLR</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        India — HI
                    </td>
                    <td>DSLR</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        Indonesia — EN
                    </td>
                    <td>DSLR</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        Indonesia — BAHASA
                    </td>
                    <td>DSLR</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        Malaysia  — EN
                    </td>
                    <td>DSLR</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td class="input"><input type="checkbox" class="i-checks" name="input[]"></td>
                    <td>
                        <i class="fa fa-lock pull-right"></i>
                        Malaysia  — Malay
                    </td>
                    <td>DSLR</td>
                    <td>09 Nov 2018 0:01 (GMT +8)</td>
                    <td>09 Nov 2019 0:01 (GMT +8)</td>
                    <td><a href="#">Theodore Twombly</a></td>
                    <td>Pending</td>
                </tr>
                </tbody>
            </table>
        </div>

        <!-- Start Pagination -->
        <div class="post-pagination">
            <ul>
                <li class="nav"><a href="#"><span class="fa fa-angle-left"></span></a></li>
                <li class="page">1</li>
                <li>of</li>
                <li class="count">24</li>
                <li class="nav"><a href="#"><span class="fa fa-angle-right"></span></a></li>
            </ul>
        </div>
        <!-- End Pagination -->

    </div>
    <!-- End Ibox -->
</div>
<!-- End Content -->
</body>
</html>